### ISSUE TITLE
Apply this to more Nitter instances

### ISSUE THREAD

**Issue by cyrneko** [catppuccin/nitter#1]
Many people use more than one Nitter instance, through e.g LibRedirect, especially as Nitter.Net often gets rate limited

Thus, I propose adding more instances to the list, like for example the list LibRedirect includes by default, for better coverage overall

Here's a list of all non-flagged instances (None of the Auth or Cloudflare ones) that Libredirect offers:
<details>
<summary>put into <code>details</code> tag to avoid huge post</summary>

<p>https://nitter.net>/</p>
<p>https://nitter.42l.fr/</p>
<p>https://nitter.pussthecat.org/</p>
<p>https://nitter.fdn.fr/</p>
<p>https://nitter.1d4.us/</p>
<p>https://nitter.kavin.rocks/</p>
<p>https://nitter.unixfox.eu/</p>
<p>https://nitter.namazso.eu/</p>
<p>https://nitter.hu/</p>
<p>https://bird.trom.tf/</p>
<p>https://nitter.it/</p>
<p>https://twitter.censors.us/</p>
<p>https://nitter.grimneko.de/</p>
<p>https://n.hyperborea.cloud/</p>
<p>https://nitter.ca/</p>
<p>https://twitter.076.ne.jp/</p>
<p>https://nitter.mstdn.social/</p>
<p>https://nitter.fly.dev/</p>
<p>https://nitter.weiler.rocks/</p>
<p>https://nitter.sethforprivacy.com/</p>
<p>https://nttr.stream/</p>
<p>https://nitter.cutelab.space/</p>
<p>https://nitter.nl/</p>
<p>https://nitter.mint.lgbt/</p>
<p>https://nitter.bus-hit.me/</p>
<p>https://nitter.esmailelbob.xyz/</p>
<p>https://tw.artemislena.eu/</p>
<p>https://de.nttr.stream/</p>
<p>https://nitter.tiekoetter.com/</p>
<p>https://nitter.spaceint.fr/</p>
<p>https://nitter.privacy.com.de/</p>
<p>https://nitter.mastodon.pro/</p>
<p>https://nitter.notraxx.ch/</p>
<p>https://nitter.poast.org/</p>
<p>https://nitter.bird.froth.zone/</p>
<p>https://nitter.dcs0.hu/</p>
<p>https://twitter.beparanoid.de/</p>
<p>https://n.ramle.be/</p>
<p>https://nitter.cz/</p>
<p>https://nitter.privacydev.net/</p>
<p>https://tweet.lambda.dance/</p>
<p>https://nitter.ebnar.xyz/</p>
<p>https://nitter.kylrth.com/</p>
<p>https://nitter.oishi-ra.men/</p>
<p>https://nitter.foss.wtf/</p>
<p>https://nitter.priv.pw/</p>
<p>https://t.com.sb/
</details>

**Comment by AnubisNekhet** [comment]
Seems good, I'll start working on it.

**Comment by AnubisNekhet** [comment]
Side note: I might consider using regex if I feel the need to reduce the number of selectors and define the exceptions individually, but I will have to confirm whether any other (major) websites have the phrase `https://nitter.` in their urls.
